// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSyOI--9c_rl6CxOxMNTzUUW1Nf1Bvyb8',
    appId: '1:379629546467:web:040df61e0c13039bd20ed6',
    messagingSenderId: '379629546467',
    projectId: 'fir-authentication-6a6d7',
    authDomain: 'fir-authentication-6a6d7.firebaseapp.com',
    storageBucket: 'fir-authentication-6a6d7.appspot.com',
    measurementId: 'G-VGT6G7KNMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB3rzPkKnED8Sb6qpKrn0uVyMSof2bVEA',
    appId: '1:379629546467:android:92f45e067a129d2ed20ed6',
    messagingSenderId: '379629546467',
    projectId: 'fir-authentication-6a6d7',
    storageBucket: 'fir-authentication-6a6d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzmkNCw-GMv4epK5REdOg3VQWGYOrfvQA',
    appId: '1:379629546467:ios:1c160b174bb78560d20ed6',
    messagingSenderId: '379629546467',
    projectId: 'fir-authentication-6a6d7',
    storageBucket: 'fir-authentication-6a6d7.appspot.com',
    iosBundleId: 'com.example.firebasePhoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzmkNCw-GMv4epK5REdOg3VQWGYOrfvQA',
    appId: '1:379629546467:ios:c6c74d2db7ce74e9d20ed6',
    messagingSenderId: '379629546467',
    projectId: 'fir-authentication-6a6d7',
    storageBucket: 'fir-authentication-6a6d7.appspot.com',
    iosBundleId: 'com.example.firebasePhoneAuth.RunnerTests',
  );
}
